server:
  port: 8090

spring:
  application:
    name: keycloak-event-listener
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 1
        batch.size: 16384
        buffer.memory: 33554432

logging:
  level:
    ru.larkin.keycloakeventlistener: DEBUG
    org.apache.kafka: WARN
