name: Messaging Service CI

on:
  push:
    paths:
      - 'services/messaging-service/**'
      - 'build-logic/**'
      - 'common/**'
  pull_request:
    paths:
      - 'services/messaging-service/**'
      - 'build-logic/**'
      - 'common/**'

jobs:
  ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      service-name: messaging-service
      needs-postgres: true
      needs-kafka: true
      test-db-name: messages_test
